
module.exports = {
  seven_color_cross_fade: 37,
  red_gradual_change: 38,
  green_gradual_change: 39,
  blue_gradual_change: 40,
  yellow_gradual_change: 41,
  cyan_gradual_change: 42,
  purple_gradual_change: 43,
  white_gradual_change: 44,
  red_green_cross_fade: 45,
  red_blue_cross_fade: 46,
  green_blue_cross_fade: 47,
  seven_color_strobe_flash: 48,
  red_strobe_flash: 49,
  green_strobe_flash: 50,
  blue_stobe_flash: 51,
  yellow_strobe_flash: 52,
  cyan_strobe_flash: 53,
  purple_strobe_flash: 54,
  white_strobe_flash: 55,
  seven_color_jumping: 56,
}
